---
title: "devtesting"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(mantis)
```

```{r}
data("example_prescription_numbers")

df <- example_prescription_numbers

```



```{js}
// when browser window is resized, all dygraphs on inactive tabs disappear. Reload page to redraw them all.
// unfortunately this also means you lose your active tab
window.onresize = function(){ location.reload(); }
```

# {.tabset .tabset-pills}

## explicit max timepoint_limit

```{r, results = 'asis'}
mantis::bespoke_rmd_output(
  df,
  inputspec = mantis::inputspec(
    timepoint_col = "PrescriptionDate",
    item_cols = c("Location", "Antibiotic", "Spectrum"),
    value_col = "NumberOfPrescriptions"
  ),
  outputspec = mantis::outputspec_interactive(),
  timepoint_limits = c(NA, Sys.Date()),
  tab_level = 2
)

```


## tab group with parent {.tabset}


```{r, results = 'asis'}
mantis::bespoke_rmd_output(
  df,
  inputspec = mantis::inputspec(
    timepoint_col = "PrescriptionDate",
    item_cols = c("Location", "Antibiotic", "Spectrum"),
    value_col = "NumberOfPrescriptions"
  ),
  outputspec = mantis::outputspec_interactive(),
  tab_name = "single parent",
  tab_level = 2
)

```

```{r, results = 'asis'}
mantis::bespoke_rmd_output(
  df,
  inputspec = mantis::inputspec(
    timepoint_col = "PrescriptionDate",
    item_cols = c("Location", "Antibiotic", "Spectrum"),
    value_col = "NumberOfPrescriptions",
    tab_col = "Location"
  ),
  outputspec = mantis::outputspec_interactive(),
  tab_name = "tab parent",
  tab_level = 2
)

```

```{r, results = 'asis'}
mantis::bespoke_rmd_output(
  df,
  inputspec = mantis::inputspec(
    timepoint_col = "PrescriptionDate",
    item_cols = c("Location", "Antibiotic", "Spectrum"),
    value_col = "NumberOfPrescriptions",
    tab_col = "Location"
  ),
  alertspec = alertspec(
      alert_rules = alert_rules(alert_missing(extent_type = "all",
                                           items = NULL))
  ),
  outputspec = mantis::outputspec_interactive(),
  tab_name = "tab parent plus alerts",
  tab_level = 2
)

```

```{r, results = 'asis'}
mantis::bespoke_rmd_output(
  df,
  inputspec = mantis::inputspec(
    timepoint_col = "PrescriptionDate",
    item_cols = c("Location", "Antibiotic", "Spectrum"),
    value_col = "NumberOfPrescriptions",
    tab_col = "Location"
  ),
  alertspec = alertspec(
      alert_rules = alert_rules(alert_missing(extent_type = "all",
                                           items = NULL)),
      show_tab_results = NULL
  ),
  outputspec = mantis::outputspec_interactive(),
  tab_name = "tab parent alerts but no alert tab",
  tab_level = 2
)

```

## tab group child tabs only {.tabset}

```{r, results = 'asis'}
mantis::bespoke_rmd_output(
  df,
  inputspec = mantis::inputspec(
    timepoint_col = "PrescriptionDate",
    item_cols = c("Location", "Antibiotic", "Spectrum"),
    value_col = "NumberOfPrescriptions",
    tab_col = "Location"
  ),
  outputspec = mantis::outputspec_interactive(),
  alertspec = alertspec(
      alert_rules = alert_rules(alert_missing(extent_type = "all",
                                           items = NULL))
  ),
  tab_level = 2
)

```


```{r, results = 'asis'}
mantis::bespoke_rmd_alert_results(
  df,
  inputspec = mantis::inputspec(
    timepoint_col = "PrescriptionDate",
    item_cols = c("Location", "Antibiotic", "Spectrum"),
    value_col = "NumberOfPrescriptions",
    tab_col = "Location"
  ),
  alert_rules = alert_rules(alert_missing(extent_type = "all",
                                           items = NULL)),
  filter_results = "FAIL",
  tab_name = "Fails only",
  tab_level = 1
)

```

```{r}
# initialise htmlwidgets otherwise they won't render
# this chunk can be placed anywhere
mantis::bespoke_rmd_initialise_widgets(plot_type = "bar")
```
