---
title: "Example heatmap report"
---

```{r example-options, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = FALSE
)
```

```{r example-setup}
library(mantis)
```

```{r generate-report}
data("example_prescription_numbers")

filename <- 
  mantis_report(
  df = example_prescription_numbers,
  inputspec = inputspec(
    timepoint_col = "PrescriptionDate",
    item_col = "Antibiotic",
    value_col = "NumberOfPrescriptions",
    tab_col = "Location"
  ),
  outputspec = outputspec_static_heatmap(
    y_label = "Antibiotic"
  ),
  report_title = "Example mantis report - heatmap",
  dataset_description = "Antibiotic prescriptions by site",
  save_directory = "../../docs/articles",
  save_filename = "example-prescriptions-static-heatmap",
  show_progress = FALSE
)

```

```{css hide-header-logo, echo=FALSE}
img.logo {
	display: none;
	}
```

```{=html}
<iframe src="https://phuongquan.github.io/mantis/articles/example-prescriptions-static-heatmap.html" width="100%" height="900">
</iframe>
```

